services:

    php:
        container_name: ${APP_NAME}-php
        volumes:
            -  .:/var/www/html
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            -  ${APP_PORT}:80
        networks:
            - mysql_net
            - redis_net
            - rabbitmq_net

        depends_on:
            - db

    rabbitmq:
        container_name: ${APP_NAME}-rabbitmq
        image: rabbitmq:3-management
        volumes:
            - rabbitmq_volume:/var/lib/rabbitmq/
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
            RABBITMQ_DEFAULT_PASS : ${RABBIT_MQ_PASSWORD}
        ports:
            - ${RABBIT_MQ_PORT}:5672
            - ${RABBIT_MQ_EXTERNAL_PORT}:15672
        restart: always

    redis:
        container_name: ${APP_NAME}-redis
        image: redis:7.2-alpine
        volumes:
            - redis_volume:/data
        command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
        ports:
            - ${REDIS_PORT}:6379
        restart: always
        networks:

    db:
        container_name: ${APP_NAME}-mysql
        image: mysql:8.4.2
        environment:
            MYSQL_HOST: ${DB_HOST}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD:
            MYSQL_RANDOM_ROOT_PASSWORD :
        volumes:
            - db_volume:/var/lib/mysql
        ports:
            - ${DB_PORT}:3306
        networks:
           - mysql_net

        restart: always
    grafana:
        container_name: ${APP_NAME}-grafana
        image: grafana/grafana:10.2.2
        ports:
            - 3000:3000
        networks:
            - mysql_net
            - redis_net
            - rabbitmq_net

        restart: always
        volumes:
            - grafana_volume:/var/lib/grafana
volumes:
    db_volume:
    redis_volume:
    rabbitmq_volume:
    grafana_volume:

networks:
    mysql_net:
        driver: bridge
    rabbitmq_net:
        driver: bridge
    redis_net:
        driver: bridge
